citygml_zip_name = "15202_nagaoka-shi_city_2024_citygml_1_op_bldg.zip"

[tests.cesium_statistics]

[tests.cesium_attributes.casts]
".attributes" = "json"

[filter.tree]
"udx/bldg/" = ["55386678_bldg_6697_op.gml"]
