# test fld (flood risk)
citygml_zip_name = "16202_takaoka-shi_city_2024_citygml_1_op_fld.zip"

[tests.cesium.casts]
".attributes" = "json"
".dm_attributes" = "json"
".uro:rank_code" = "string"

[tests.json_attributes_v2.dictionary]
flow.path = "flow/dictionary.json"
truth.path = "dictionary.json"
casts.fld = { comparator = "list_to_dict", key = ".name" }

[tests.json_attributes_v2.tilesets_l2_no_texture]
flow.path = "flow_extracted/16202_takaoka-shi_city_2024_citygml_1_op_fld_pref_oyabegawa_gandogawa_3dtiles_l2_no_texture/tileset.json"
flow.json_path = ".properties"
truth.path = "3dtiles_l2_no_texture_tileset.json"

[filter.tree]
"udx/fld/pref/oyabegawa_gandogawa/55360704_fld_6697_l2.gml" = [
    "fld_3dab99fd-de9f-4806-9b10-7befb7cb4c87",
]
