citygml_zip_name = "13421_ogasawara-mura_pref_2025_citygml_1_op_bldg.zip"

[tests.json_attributes_v2.tilesets_lod1]
flow.path = "flow_extracted/13421_ogasawara-mura_pref_2025_citygml_1_op_bldg_3dtiles_lod1/tileset.json"
flow.json_path = ".properties"
truth.path = "3dtiles_lod1_tileset.json"

[tests.cesium.casts]
".attributes" = "json"
".attributes.meshcode" = "string"
".uro:BuildingDetailAttribute_uro:surveyYear" = "int"
".attributes.uro:BuildingDetailAttribute[0].uro:buildingRoofEdgeArea" = "float"

[filter.tree]
"udx/bldg" = ["40425105_bldg_6697_op.gml"]
