citygml_zip_name = "13421_ogasawara-mura_pref_2025_citygml_1_op_bldg.zip"

[tests.json_attributes.tilesets]
path = "13421_ogasawara-mura_pref_2025_citygml_1_op_bldg_3dtiles_lod1/tileset.json"
extracted = true

[tests.json_attributes.tilesets.casts]
".geometricError" = "ignore_both"
".root" = "ignore_both"
".properties.uro:BuildingDetailAttribute_uro:surveyYear" = "ignore_both"

[tests.cesium.casts]
".attributes" = "json"
".attributes.meshcode" = "string"
".uro:BuildingDetailAttribute_uro:surveyYear" = "int"
".attributes.uro:BuildingDetailAttribute[0].uro:buildingRoofEdgeArea" = "float"

[filter.tree]
"udx/bldg" = ["40425105_bldg_6697_op.gml"]
