# test rfld (reservoir flood risk)
citygml_zip_name = "12206_kisarazu-shi_city_2024_citygml_1_op_rfld.zip"

[tests.cesium.casts]
".attributes" = "json"
".dm_attributes" = "json"
".uro:rank_code" = "string"


[tests.json_attributes_v2.dictionary]
flow.path = "flow/dictionary.json"
truth.path = "dictionary.json"
casts.rfld = { comparator = "list_to_dict", key = ".name" }

[tests.json_attributes_v2.tilesets_no_texture]
flow.path = "flow_extracted/12206_kisarazu-shi_city_2024_citygml_1_op_rfld_12_4_3dtiles_no_texture/tileset.json"
flow.json_path = ".properties"
truth.path = "3dtiles_no_texture_tileset.json"

[filter.tree]
"udx/rfld/12_4/534000_rfld_6697_op.gml" = [
    "rfld_71222538-3c3a-43ba-821c-f07e39e3a4be",
]
