citygml_zip_name = "13102_chuo-ku_pref_2023_citygml_2_op_ubld.zip"

[tests.cesium_statistics]

[tests.cesium_attributes.casts]
".attributes" = "json"

[filter.tree]
"udx/ubld/" = ["53394611_ubld_6697_op.gml"]
