# test tnm (tsunami risk)
citygml_zip_name = "12206_kisarazu-shi_city_2024_citygml_1_op_tnm.zip"

[tests.cesium_attributes.casts]
".attributes" = "json"
".dm_attributes" = "json"

[tests.cesium_statistics]

[tests.json_attributes.dictionary]
path = "dictionary.json"
[tests.json_attributes.dictionary.casts.".tnm"]
comparator = "list_to_dict"
key = ".name"

[filter.tree]
"udx/tnm/12_1/" = ["523977_tnm_6697_op.gml"]
