# test tnm (tsunami risk)
citygml_zip_name = "12206_kisarazu-shi_city_2024_citygml_1_op_tnm.zip"

[tests.cesium_attributes.casts]
".attributes" = "json"
".dm_attributes" = "json"
".uro:rank_code" = "string"

[tests.cesium_statistics]

[tests.json_attributes.dictionary]
path = "dictionary.json"
[tests.json_attributes.dictionary.casts.".tnm"]
comparator = "list_to_dict"
key = ".name"

[tests.json_attributes.tilesets]
path = "12206_kisarazu-shi_city_2024_citygml_1_op_tnm_12_1_3dtiles_no_texture/tileset.json"
extracted = true

[tests.json_attributes.tilesets.casts]
".geometricError" = "ignore_both"
".root" = "ignore_both"

[tests.json_attributes.tilesets.values]
".properties.uro:rank_code" = {} # FME silently convert this to number type, causing min/max values to appear

[filter.tree]
"udx/tnm/12_1/" = ["523977_tnm_6697_op.gml"]
