citygml_zip_name = "15202_nagaoka-shi_city_2024_citygml_1_op_unf.zip"

[tests.json_attributes.dictionary]
path = "dictionary.json"

[tests.cesium.casts]
".attributes" = "json"
".attributes.meshcode" = "string"

[filter.tree]
"udx/unf/" = ["08EE752_unf_10169_sewer_op.gml"]
