citygml_zip_name = "43206_tamana-shi_city_2024_citygml_2_op_brid.zip"

[tests.cesium_statistics]

[tests.cesium_attributes.casts]
".attributes" = "json"
".attributes.meshcode" = "string"

[tests.mvt_polygons]
threshold = 0.001

[tests.json_attributes.tilesets_lod3]
path = "43206_tamana-shi_city_2024_citygml_2_op_brid_3dtiles_lod3/tileset.json"
extracted = true

[tests.json_attributes.tilesets_lod3.casts]
".geometricError" = "ignore_both"
".root" = "ignore_both"

[filter.tree]
"udx/brid/" = ["49303414_brid_6697_op.gml", "49303414_brid_6697_appearance/"]
