citygml_zip_name = "16202_takaoka-shi_city_2024_citygml_1_op.zip"
workflow_path = "runtime/examples/fixture/workflow/data-convert/plateau4/02-tran-rwy-trk-squr-wwy/workflow.yml"

# [tests.mvt_lines]
# threshold = 0.02
# zoom = [13, 16] # test from 13 to avoid thin runway polygons
# 
# [tests.mvt_polygons]
# threshold = 0.001

[tests.mvt_attributes.casts]
".attributes" = "json"

[filter.tree]
"" = ["codelists/", "schemas/"]
"udx/rwy/" = [
  "55360718_rwy_6697.gml",
  "55360728_rwy_6697.gml",
  "55360733_rwy_6697.gml",
]
