citygml_zip_name = "15202_nagaoka-shi_city_2024_citygml_1_op_bldg.zip"

[tests.cesium_statistics]

[tests.cesium_attributes.casts]
".attributes" = "json"
".uro_BuildingDetailAttribute_uro_surveyYear" = "string" # ignore

[filter.tree]
"udx/bldg/55386678_bldg_6697_op.gml" = ["bldg_125ea37f-cb34-4d85-8c1a-d9f22aa5f050"]
