citygml_zip_name = "14212_atsugi-shi_city_2023_citygml_2_op.zip"
workflow_path = "runtime/examples/fixture/workflow/data-convert/plateau4/02-tran-rwy-trk-squr-wwy/workflow.yml"

[tests.mvt_polygons]
threshold = 0.001

[tests.mvt_lines]
threshold = 0.001

[tests.mvt_attributes.casts]
".attributes" = "json"

[filter.tree]
"" = ["codelists/", "schemas/"]
"udx/squr/533912_squr_6697_op.gml" = [
  "squr_e899eb74-d5ec-498e-8268-634c0222aaa0",
  "squr_20151e0d-cca1-4baa-a8be-b81e5ebad749",
]
