# test htd (high tide risk)
citygml_zip_name = "12206_kisarazu-shi_city_2024_citygml_1_op_htd.zip"

[tests.cesium.casts]
".attributes" = "json"
".dm_attributes" = "json"

[tests.json_attributes_v2.dictionary]
flow.path = "flow/dictionary.json"
truth.path = "dictionary.json"
casts.htd = { comparator = "list_to_dict", key = ".name" }

[tests.json_attributes_v2.tilesets_no_texture]
flow.path = "flow_extracted/12206_kisarazu-shi_city_2024_citygml_1_op_htd_12_1_3dtiles_no_texture/tileset.json"
flow.json_path = ".properties"
truth.path = "3dtiles_no_texture_tileset.json"

[filter.tree]
"udx/htd/12_1/523977_htd_6697_op.gml" = [
    "htd_a4d40683-e49f-4f5a-a896-2d83083aa00b",
]
