# test htd (high tide risk)
citygml_zip_name = "12206_kisarazu-shi_city_2024_citygml_1_op_htd.zip"

[tests.cesium_attributes.casts]
".attributes" = "json"
".dm_attributes" = "json"

[tests.cesium_statistics]

[tests.json_attributes.dictionary]
path = "dictionary.json"
[tests.json_attributes.dictionary.casts.".htd"]
comparator = "list_to_dict"
key = ".name"

[filter.tree]
"udx/htd/12_1/523977_htd_6697_op.gml" = [
    "htd_a4d40683-e49f-4f5a-a896-2d83083aa00b",
]
