[package]
description = "Re:Earth Flow geometry library"
name = "reearth-flow-geometry"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reearth-flow-common.workspace = true

flatgeom.workspace = true
nusamai-projection.workspace = true

approx.workspace = true
bytes.workspace = true
clipper-sys.workspace = true
float_next_after.workspace = true
geo-buffer.workspace = true
geo-types.workspace = true
geojson.workspace = true
i_overlay.workspace = true
nalgebra.workspace = true
num-traits.workspace = true
parking_lot.workspace = true
robust.workspace = true
rstar.workspace = true
serde.workspace = true
serde_json.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
