# test ifld (inland flood risk)
citygml_zip_name = "11100_saitama-shi_city_2024_citygml_1_op_ifld.zip"

[tests.cesium.casts]
".attributes" = "json"
".dm_attributes" = "json"
".uro:rankOrg_code" = "string"

[tests.json_attributes_v2.dictionary]
flow.path = "flow/dictionary.json"
truth.path = "dictionary.json"
casts.ifld = { comparator = "list_to_dict", key = ".name" }

[tests.json_attributes_v2.tilesets_no_texture]
flow.path = "flow_extracted/11100_saitama-shi_city_2024_citygml_1_op_ifld_11_1_3dtiles_no_texture/tileset.json"
flow.json_path = ".properties"
truth.path = "3dtiles_no_texture_tileset.json"

[filter.tree]
"udx/ifld/11_1/533955_ifld_6697_op.gml" = [
    "ifld_36544caf-3eb1-4f08-85aa-7b6989a2c405",
]
