[package]
description = "Re:Earth Flow telemetry library"
name = "reearth-flow-telemetry"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.0.2"

[dependencies]
once_cell.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry-stdout.workspace = true
opentelemetry_sdk.workspace = true
serde.workspace = true
thiserror.workspace = true
