[package]
description = "Re:Earth Flow common library"
name = "reearth-flow-common"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
approx.workspace = true
async-recursion.workspace = true
async_zip.workspace = true
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
colorsys.workspace = true
directories.workspace = true
futures.workspace = true
home.workspace = true
image.workspace = true
jsonpath_lib.workspace = true
libxml.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
walkdir.workspace = true
zip.workspace = true
zstd.workspace = true
