# test dm geometric attributes
citygml_zip_name = "08220_tsukuba-shi_city_2023_citygml_2_op.zip"

[tests.mvt_lines]
zoom = [12, 16]
threshold = 0.01
# 
# [tests.mvt_polygons]
# zoom = [12, 16]
# threshold = 0.01

[tests.mvt_attributes.casts]
".attributes" = "json"
".dm_attributes" = "json"

[filter.tree]
"" = ["codelists/", "schemas/"]
"udx/trk/54401008_trk_6697_op.gml" = ["trk_c2138494-83e0-41b4-bfc1-609ca229aba2"]
