# test dm geometric attributes
citygml_zip_name = "08220_tsukuba-shi_city_2023_citygml_2_op_trk.zip"

[tests.mvt_lines]
zoom = [12, 16]
threshold = 0.01

[tests.mvt_polygons]
zoom = [12, 16]
threshold = 0.01

[tests.mvt_attributes.casts]
".attributes" = "json"
".attributes.meshcode" = "string"
".attributes.ancestors[0].meshcode" = "string"
".dm_attributes" = "json"

[tests.cesium.casts]
".attributes" = "json"
".dm_attributes" = "json"
".attributes.meshcode" = "string"
".attributes.ancestors[0].meshcode" = "string"


[tests.json_attributes_v2.tilesets_lod3]
flow.path = "flow_extracted/08220_tsukuba-shi_city_2023_citygml_2_op_trk_3dtiles_lod3/tileset.json"
flow.json_path = ".properties"
truth.path = "3dtiles_lod3_tileset.json"

[filter.tree]
"udx/trk/54401008_trk_6697_op.gml" = ["trk_c2138494-83e0-41b4-bfc1-609ca229aba2"]
