citygml_zip_name = "13421_ogasawara-mura_pref_2025_citygml_1_op_lsld.zip"

[tests.mvt_attributes.casts]
".attributes" = "json"
".attributes.meshcode" = "string"

[tests.mvt_polygons]
threshold = 0.001

[filter.tree]
"udx/lsld/" = ["394271_lsld_6697_op.gml"]
